package ast

const (
	DOCUMENT               = "Document"
	OPERATION_DEFINITION   = "OperationDefinition"
	OBJECT_DEFINITION      = "ObjectDefinition"
	FIELD_DEFINITION       = "FieldDefinition"
	INPUT_VALUE_DEFINITION = "InputValueDefinition"
	VARIABLE               = "Variable"
	NAME                   = "Name"
	FIELD                  = "Field"
	SELECTION_SET          = "SelectionSet"
	FRAGMENT_SPREAD        = "FragmentSpread"
	INLINE_FRAGMENT        = "InlineFragment"
	NAMED_TYPE             = "NamedType"
	LIST_TYPE              = "ListType"
	NONNULL_TYPE           = "NonNullType"
	DIRECTIVE              = "Directive"
	ARGUMENT               = "Argument"
	STRING_VALUE           = "StringValue"
	ENUM_VALUE             = "EnumValue"
	BOOLEAN_VALUE          = "BooleanValue"
	INT_VALUE              = "IntValue"
	FLOAT_VALUE            = "FloatValue"
)
